"""Task 4.7 - image-based alignment fallbacks against synthetic line art.

Ground truth pairs are generated by drawing a synthetic line-art "sheet" and
warping it with a *known* 3x3 similarity matrix (old -> new). Every test then
measures the recovered matrix against ground truth either through decomposed
parameters or through the RMS point-mapping error over the whole sheet
(``_point_rms``), which is immune to centre-vs-origin convention confusion.

The synthetic sheets deliberately carry realistic CAD-like structure (large
axis-aligned room rectangles, diagonal hatching, clutter lines) because
rotation recovery from the FFT magnitude spectrum needs directional content;
uniformly random strokes are spectrally near-isotropic and carry almost no
rotation information. The features tests additionally plant distinct corner
markers (unique glyphs inside filled squares) because plain rectangles give
SIFT too few distinctive keypoints - the honest caveat documented in
``align_features``.
"""

from __future__ import annotations

import math

import cv2
import numpy as np
import pytest

from engine.align.image_align import (
    align_features,
    align_phase_correlation,
    align_sheet_border,
)
from engine.align.types import AlignConfig, AlignMethod

# ── synthetic content and ground truth ──────────────────────────────────


def _drawing(width: int, height: int, seed: int, thickness: int = 6) -> np.ndarray:
    """CAD-like line art on white: rooms, diagonals, clutter lines."""
    img = np.full((height, width), 255, np.uint8)
    rng = np.random.default_rng(seed)
    mx, my = int(width * 0.16), int(height * 0.16)
    x0, y0, x1e, y1e = mx, my, width - mx, height - my
    for _ in range(5):
        rw = int(rng.integers(width * 0.08, width * 0.20))
        rh = int(rng.integers(height * 0.08, height * 0.20))
        rx = int(rng.integers(x0, x1e - rw))
        ry = int(rng.integers(y0, y1e - rh))
        cv2.rectangle(img, (rx, ry), (rx + rw, ry + rh), 0, thickness)
        inner = max(1, thickness - 1)
        cv2.rectangle(
            img,
            (rx + int(0.06 * rw), ry + int(0.06 * rh)),
            (rx + rw - int(0.06 * rw), ry + rh - int(0.06 * rh)),
            0,
            inner,
        )
    for _ in range(24):
        x1 = int(rng.integers(x0, x0 + 0.6 * (x1e - x0)))
        y1 = int(rng.integers(y0, y0 + 0.6 * (y1e - y0)))
        x2 = int(rng.integers(x0 + 0.4 * (x1e - x0), x1e))
        y2 = int(rng.integers(y0 + 0.4 * (y1e - y0), y1e))
        cv2.line(img, (x1, y1), (x2, y2), 0, max(1, thickness - 1))
    for _ in range(30):
        if rng.random() < 0.5:
            y = int(rng.integers(y0, y1e))
            cv2.line(img, (x0 + 5, y), (x1e - 5, y), 0, max(1, thickness - 1))
        else:
            x = int(rng.integers(x0, x1e))
            cv2.line(img, (x, y0 + 5), (x, y1e - 5), 0, max(1, thickness - 1))
    return img


def _marker_drawing(width: int, height: int, seed: int) -> np.ndarray:
    """Line art plus five distinctive corner markers for feature matching."""
    img = _drawing(width, height, seed, thickness=4)
    mx, my = int(width * 0.14), int(height * 0.14)
    size = 44
    markers = [
        (mx + 10, my + 10, "ring"),
        (width - mx - 10 - size, my + 10, "cross"),
        (mx + 10, height - my - 10 - size, "checker"),
        (width - mx - 10 - size, height - my - 10 - size, "plus"),
        (width // 2 - size // 2, my + 10, "square"),
    ]
    for x, y, kind in markers:
        cv2.rectangle(img, (x, y), (x + size, y + size), 0, -1)
        half = size // 2
        if kind == "ring":
            cv2.circle(img, (x + half, y + half), size // 4, 255, -1)
        elif kind == "cross":
            cv2.line(img, (x, y), (x + size, y + size), 255, 6)
            cv2.line(img, (x + size, y), (x, y + size), 255, 6)
        elif kind == "checker":
            for row in range(2):
                for col in range(2):
                    if (row + col) % 2 == 0:
                        cv2.rectangle(
                            img,
                            (x + col * half, y + row * half),
                            (x + (col + 1) * half, y + (row + 1) * half),
                            255,
                            -1,
                        )
        elif kind == "plus":
            cv2.rectangle(img, (x + half - 8, y + 4), (x + half + 8, y + size - 4), 255, -1)
            cv2.rectangle(img, (x + 4, y + half - 8), (x + size - 4, y + half + 8), 255, -1)
    return img


def _similarity(
    width: float,
    height: float,
    angle_deg: float,
    scale: float,
    tx: float = 0.0,
    ty: float = 0.0,
) -> np.ndarray:
    """Known old->new similarity: rotate + scale about centre, then translate."""
    radians = math.radians(angle_deg)
    cx, cy = width / 2.0, height / 2.0
    matrix = np.eye(3, dtype=float)
    matrix[0, 0] = scale * math.cos(radians)
    matrix[0, 1] = -scale * math.sin(radians)
    matrix[1, 0] = scale * math.sin(radians)
    matrix[1, 1] = scale * math.cos(radians)
    matrix[0, 2] = cx - matrix[0, 0] * cx - matrix[0, 1] * cy + tx
    matrix[1, 2] = cy - matrix[1, 0] * cx - matrix[1, 1] * cy + ty
    return matrix


def _warp(img: np.ndarray, matrix: np.ndarray) -> np.ndarray:
    height, width = img.shape
    return cv2.warpAffine(
        img,
        matrix[:2].astype(np.float64),
        (width, height),
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=255,
    )


def _point_rms(
    estimate: np.ndarray, truth: np.ndarray, width: int, height: int, n: int = 300
) -> float:
    """RMS distance over random sheet points mapped by both matrices."""
    rng = np.random.default_rng(0)
    points = np.column_stack([rng.uniform(0, width, n), rng.uniform(0, height, n)])
    homogeneous = np.column_stack([points, np.ones(n)])
    est = (homogeneous @ estimate.T)[:, :2]
    ref = (homogeneous @ truth.T)[:, :2]
    return float(np.sqrt(np.mean(np.sum((est - ref) ** 2, axis=1))))


def _rotation_scale(matrix: np.ndarray) -> tuple[float, float]:
    a, c = matrix[0, 0], matrix[1, 0]
    return math.degrees(math.atan2(c, a)), math.hypot(a, c)


SHEET_W, SHEET_H = 800, 600


# ── phase correlation ───────────────────────────────────────────────────


@pytest.mark.parametrize("dx,dy", [(40, 25), (60, 0)])
def test_phase_correlation_pure_translation(dx, dy):
    old = _drawing(SHEET_W, SHEET_H, seed=9)
    truth = _similarity(SHEET_W, SHEET_H, 0.0, 1.0, dx, dy)
    new = _warp(old, truth)
    result = align_phase_correlation(old, new)
    assert result.method is AlignMethod.PHASE_CORRELATION
    assert math.isfinite(result.rms_residual_px)
    assert result.confidence > 0.0
    assert _point_rms(result.matrix, truth, SHEET_W, SHEET_H) <= 2.0


def test_phase_correlation_rotation_8_deg():
    old = _drawing(SHEET_W, SHEET_H, seed=4)
    truth = _similarity(SHEET_W, SHEET_H, 8.0, 1.0)
    new = _warp(old, truth)
    result = align_phase_correlation(old, new)
    rot, scale = _rotation_scale(result.matrix)
    truth_rot, truth_scale = _rotation_scale(truth)
    assert abs(rot - truth_rot) <= 0.75
    assert abs(scale - truth_scale) / truth_scale <= 0.03
    assert _point_rms(result.matrix, truth, SHEET_W, SHEET_H) <= 2.0


def test_phase_correlation_scale_1_15():
    old = _drawing(SHEET_W, SHEET_H, seed=13)
    truth = _similarity(SHEET_W, SHEET_H, 0.0, 1.15)
    new = _warp(old, truth)
    result = align_phase_correlation(old, new)
    rot, scale = _rotation_scale(result.matrix)
    assert abs(rot) <= 1.0
    assert abs(scale - 1.15) / 1.15 <= 0.03
    assert _point_rms(result.matrix, truth, SHEET_W, SHEET_H) <= 2.0


def test_phase_correlation_combined_modest():
    old = _drawing(SHEET_W, SHEET_H, seed=21)
    truth = _similarity(SHEET_W, SHEET_H, 6.0, 1.10, 16, 10)
    new = _warp(old, truth)
    result = align_phase_correlation(old, new)
    rot, scale = _rotation_scale(result.matrix)
    assert abs(rot - 6.0) <= 1.0
    assert abs(scale - 1.10) / 1.10 <= 0.04
    assert _point_rms(result.matrix, truth, SHEET_W, SHEET_H) <= 3.0


def test_phase_correlation_color_input():
    old = _drawing(SHEET_W, SHEET_H, seed=33)
    truth = _similarity(SHEET_W, SHEET_H, 0.0, 1.0, 40, 25)
    new = _warp(old, truth)
    old_bgr = cv2.cvtColor(old, cv2.COLOR_GRAY2BGR)
    new_bgr = cv2.cvtColor(new, cv2.COLOR_GRAY2BGR)
    result = align_phase_correlation(old_bgr, new_bgr)
    assert _point_rms(result.matrix, truth, SHEET_W, SHEET_H) <= 2.0


def test_phase_correlation_different_sizes_fails():
    old = _drawing(SHEET_W, SHEET_H, seed=9)
    new = _warp(old, _similarity(SHEET_W, SHEET_H, 0.0, 1.0, 40, 25))[:500, :]
    result = align_phase_correlation(old, new)
    assert result.method is AlignMethod.PHASE_CORRELATION
    assert not math.isfinite(result.rms_residual_px)
    assert result.note


# ── feature matching ────────────────────────────────────────────────────


def test_features_recovers_translation():
    old = _marker_drawing(SHEET_W, SHEET_H, seed=5)
    truth = _similarity(SHEET_W, SHEET_H, 0.0, 1.0, 40, 25)
    new = _warp(old, truth)
    result = align_features(old, new, config=AlignConfig(coarse_scale=0.5))
    assert result.method is AlignMethod.FEATURES
    assert result.inlier_count >= 3
    assert result.inlier_ratio > 0.0
    assert _point_rms(result.matrix, truth, SHEET_W, SHEET_H) <= 3.0


def test_features_at_default_coarse():
    old = _marker_drawing(SHEET_W, SHEET_H, seed=5)
    truth = _similarity(SHEET_W, SHEET_H, 0.0, 1.0, 40, 25)
    new = _warp(old, truth)
    result = align_features(old, new)
    assert result.method is AlignMethod.FEATURES
    assert _point_rms(result.matrix, truth, SHEET_W, SHEET_H) <= 3.0


def test_features_orb_option():
    old = _marker_drawing(SHEET_W, SHEET_H, seed=5)
    truth = _similarity(SHEET_W, SHEET_H, 0.0, 1.0, 40, 25)
    new = _warp(old, truth)
    result = align_features(old, new, detector="orb", config=AlignConfig(coarse_scale=0.5))
    assert result.method is AlignMethod.FEATURES
    assert result.inlier_count >= 3
    assert _point_rms(result.matrix, truth, SHEET_W, SHEET_H) <= 5.0


def test_features_honest_failure_on_plain_rectangles():
    # The docstring caveat: plain rectangles give SIFT little to hold on to,
    # so without markers the fallback may legitimately fail.
    old = _drawing(SHEET_W, SHEET_H, seed=5, thickness=6)
    new = _warp(old, _similarity(SHEET_W, SHEET_H, 0.0, 1.0, 40, 25))
    result = align_features(old, new)
    if result.method is AlignMethod.FEATURES:
        assert math.isfinite(result.rms_residual_px)
    else:
        assert not math.isfinite(result.rms_residual_px)
        assert result.note


# ── sheet border ────────────────────────────────────────────────────────


def test_sheet_border_recovers_shifted_frame():
    old = np.full((SHEET_H, SHEET_W), 255, np.uint8)
    cv2.rectangle(old, (80, 60), (720, 540), 0, 6)
    cv2.rectangle(old, (100, 90), (700, 510), 0, 3)
    new = np.full((SHEET_H, SHEET_W), 255, np.uint8)
    cv2.rectangle(new, (150, 105), (790, 585), 0, 6)
    cv2.rectangle(new, (170, 135), (770, 555), 0, 3)
    result = align_sheet_border(old, new)
    assert result.method is AlignMethod.SHEET_BORDER
    assert result.confidence == 0.4
    assert "frame" in result.note
    truth = _similarity(SHEET_W, SHEET_H, 0.0, 1.0, 70, 45)
    assert _point_rms(result.matrix, truth, SHEET_W, SHEET_H) <= 2.0


def test_sheet_border_fails_without_frame():
    old = _drawing(SHEET_W, SHEET_H, seed=9)
    new = np.full((SHEET_H, SHEET_W), 255, np.uint8)  # no ink at all
    result = align_sheet_border(old, new)
    assert result.method is AlignMethod.SHEET_BORDER
    assert not math.isfinite(result.rms_residual_px)
